#url: https://babajon.github.io
#baseurl: /agency-jekyll-theme/

# Site settings

#glynn ftp settings
markdown: rdiscount
pygments: true
auto: true

ftp_host: 'ftp.domeneshop.no'
ftp_dir: '/www'
ftp_passive: false


# optional
ftp_port: 21                  # default 21
ftp_username: 'irfansharifmirza'     # default read from stdin
ftp_password: '6YH@a&fN' # default read from stdin
ftp_secure: true              # default false


title: Irfan Mirza
email: your-email@domain.com
language_default : 'no'
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
description: "Irfan Mirza eiendomsmegler hos DNB Eindom Rodeløkka"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333
  navbar-light: fff

# Team names, titles and social links
people:
- name: Irfan Mirza
  pic: 1
  position: Eiendomsmegler
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: 
    url: 
  - title: 
    url:
  - title: 
    url: 
  - title:  
    url: 
  - title: 
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Trondheimsveien 72
  - line: 0565, Oslo

# Build settings
markdown: kramdown
permalink: pretty